name: HTML CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Validate HTML
      - name: Install tidy-html5 for validation
        run: sudo apt-get install -y tidy

      # Step 3: Run HTML validation
      - name: Validate HTML files
        run: tidy -qe index.html || true

      # Step 4: Display success message
      - name: Build complete
        run: echo "HTML validation complete!"
